---
- name: Restart networkmanager
  ansible.builtin.service:
    name: "{ networkmanager_service_name | default('networkmanager') }"
    state: restarted
  when: networkmanager_service_name | default('') | length > 0
  listen: "Restart networkmanager"
