---
- name: Restart auditd
  ansible.builtin.service:
    name: "{ auditd_service_name | default('auditd') }"
    state: restarted
  when: auditd_service_name | default('') | length > 0
  listen: "Restart auditd"
