---
- name: Restart docker
  ansible.builtin.service:
    name: "{ docker_service_name | default('docker') }"
    state: restarted
  when: docker_service_name | default('') | length > 0
  listen: "Restart docker"
