---
- name: Restart squid
  ansible.builtin.service:
    name: "{ squid_service_name | default('squid') }"
    state: restarted
  when: squid_service_name | default('') | length > 0
  listen: "Restart squid"
