---
all:
  children:
    ubuntu_servers:
      children:
        desktop:
          hosts:
            ubuntu-desktop-01:
              ansible_host: 192.0.2.10
              ansible_user: ubuntu
        server:
          hosts:
            ubuntu-server-01:
              ansible_host: 192.0.2.20
              ansible_user: ubuntu
      vars:
        ansible_connection: ssh
        ansible_become: true
        environment_type: production
