---
- name: Restart sysctl
  ansible.builtin.service:
    name: "{ sysctl_service_name | default('sysctl') }"
    state: restarted
  when: sysctl_service_name | default('') | length > 0
  listen: "Restart sysctl"
