---
- name: Restart usbguard
  ansible.builtin.service:
    name: "{ usbguard_service_name | default('usbguard') }"
    state: restarted
  when: usbguard_service_name | default('') | length > 0
  listen: "Restart usbguard"
